name: ci

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    runs_on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup ruby
        uses: ruby/setup-ruby@v1.80.0
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: setup just
        uses: extractions/setup-just@v1

      - name: test
        run: just test

      - name: lint
        run: just lint

